blueprint:
  name: ABC Emergency - Exited Zone Alert
  description: >
    Send a notification when you leave an emergency polygon zone.
    This provides peace of mind that you've moved out of the affected area.
  domain: automation
  source_url: https://github.com/troykelly/homeassistant-abcemergency/blob/main/blueprints/automation/abc_emergency_exited_zone.yaml
  input:
    notify_device:
      name: Notification Device
      description: The mobile device to send notifications to
      selector:
        device:
          filter:
            - integration: mobile_app

trigger:
  - platform: event
    event_type: abc_emergency_exited_polygon

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: "Left Emergency Zone"
    message: >
      You have left: {{ trigger.event.data.headline }}

      Stay vigilant and continue to monitor conditions.
