blueprint:
  name: ABC Emergency - Periodic Zone Reminder
  description: >
    Send periodic reminders while you remain inside an emergency zone.
    The integration fires abc_emergency_inside_polygon events on each update
    (every 5 minutes). This blueprint sends reminders for serious alerts only.
  domain: automation
  source_url: https://github.com/troykelly/homeassistant-abcemergency/blob/main/blueprints/automation/abc_emergency_periodic_zone_reminder.yaml
  input:
    notify_device:
      name: Notification Device
      description: The mobile device to send reminders to
      selector:
        device:
          filter:
            - integration: mobile_app
    minimum_alert_level:
      name: Minimum Alert Level for Reminders
      description: Only remind for this alert level or higher
      default: "severe"
      selector:
        select:
          options:
            - label: "Emergency Warning only"
              value: "extreme"
            - label: "Watch and Act or higher"
              value: "severe"
            - label: "Any warning level"
              value: "moderate"

trigger:
  - platform: event
    event_type: abc_emergency_inside_polygon

variables:
  min_level: !input minimum_alert_level
  level_priority:
    extreme: 3
    severe: 2
    moderate: 1
    minor: 0

condition:
  # Alert level filter - only trigger for configured level or higher
  - condition: template
    value_template: >
      {{ level_priority.get(trigger.event.data.alert_level, 0) >= level_priority.get(min_level, 0) }}

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: >
      {% if trigger.event.data.alert_level == 'extreme' %}
      STILL INSIDE EMERGENCY ZONE
      {% else %}
      Still Inside Emergency Zone
      {% endif %}
    message: >
      Reminder: You are still inside {{ trigger.event.data.headline }}.

      Alert level: {{ trigger.event.data.alert_text }}

      Continue to monitor conditions.
    data:
      priority: >
        {% if trigger.event.data.alert_level == 'extreme' %}high{% else %}normal{% endif %}
