blueprint:
  name: ABC Emergency - Entered Zone Alert
  description: >
    Send a notification when you enter any emergency polygon zone.
    This uses point-in-polygon detection to know when you're actually
    inside an emergency boundary, not just nearby.
  domain: automation
  source_url: https://github.com/troykelly/homeassistant-abcemergency/blob/main/blueprints/automation/abc_emergency_entered_zone.yaml
  input:
    notify_device:
      name: Notification Device
      description: The mobile device to send notifications to
      selector:
        device:
          filter:
            - integration: mobile_app

trigger:
  - platform: event
    event_type: abc_emergency_entered_polygon

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: >
      {% if trigger.event.data.alert_level == 'extreme' %}
      ENTERED EMERGENCY ZONE
      {% elif trigger.event.data.alert_level == 'severe' %}
      Entered Watch and Act Zone
      {% else %}
      Entered Emergency Zone
      {% endif %}
    message: >
      You are now inside: {{ trigger.event.data.headline }}

      Alert Level: {{ trigger.event.data.alert_text }}

      Type: {{ trigger.event.data.event_type }}
    data:
      ttl: 0
      priority: >
        {% if trigger.event.data.alert_level == 'extreme' %}critical
        {% elif trigger.event.data.alert_level == 'severe' %}high
        {% else %}normal{% endif %}
      channel: >
        {% if trigger.event.data.alert_level == 'extreme' %}alarm_stream{% else %}alerts{% endif %}
