blueprint:
  name: ABC Emergency - Severity Escalation Alert
  description: >
    Critical alert when an emergency escalates while you're inside its polygon.
    For example, when an Advice level warning becomes Watch and Act, or
    Watch and Act escalates to Emergency Warning. This is a life-safety feature.
  domain: automation
  source_url: https://github.com/troykelly/homeassistant-abcemergency/blob/main/blueprints/automation/abc_emergency_severity_escalation.yaml
  input:
    notify_device:
      name: Notification Device
      description: The mobile device to send notifications to
      selector:
        device:
          filter:
            - integration: mobile_app
    notify_deescalation:
      name: Also Notify on De-escalation
      description: Send a notification when alerts are reduced (good news)
      default: true
      selector:
        boolean:

trigger:
  - platform: event
    event_type: abc_emergency_containment_severity_changed

variables:
  notify_deescalation_var: !input notify_deescalation

action:
  - choose:
      # Escalation - more serious
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.escalated == true }}"
        sequence:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "ALERT LEVEL INCREASED"
            message: >
              {{ trigger.event.data.headline }} has ESCALATED!

              {{ trigger.event.data.previous_alert_text }} to {{ trigger.event.data.new_alert_text }}

              TAKE ACTION NOW!
            data:
              priority: critical
              ttl: 0
              channel: alarm_stream

      # De-escalation - good news (if enabled)
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.escalated == false and notify_deescalation_var }}"
        sequence:
          - device_id: !input notify_device
            domain: mobile_app
            type: notify
            title: "Alert Level Reduced"
            message: >
              {{ trigger.event.data.headline }} has de-escalated from
              {{ trigger.event.data.previous_alert_text }} to {{ trigger.event.data.new_alert_text }}.

              Continue to monitor conditions.
